### ISSUE TITLE
Improve .env file

### ISSUE THREAD

**Issue by wachterjohannes** [wachterjohannes/sulu-docker#1]
add the domain and the ports and add some documentation for this file

**Comment by Nightbr** [comment]
add to that, explain how to configure the app parameters.yml (not everyone is aware of this):

```yaml
parameters:
    database_driver: pdo_mysql
    database_host: mysql
    database_port: null
    database_name: mydb
    database_user: user
    database_password: userpass
```
