### ISSUE TITLE
Linux comptatibility (Ubuntu based distro)

### ISSUE THREAD

**Issue by Nightbr** [wachterjohannes/sulu-docker#2]
Hey,

I would like to use this on my Linux Mint (Ubuntu based) but there is some issue with unison sync on linux. Add to that the native linux sync is already performant. 

If I remove the sync_strategy in docker-sync.yml https://github.com/wachterjohannes/sulu-docker/blob/master/docker-sync.yml#L11 this will use the native linux sync and works for linux too! 

Can you test if on MacOS and Windows this line is necessary? According to docker-sync documentation by default on MacOS and Windows, it will use unison.

Thanks!

Note: another solution will be to create several docker-compose.{os}.yml

**Comment by wachterjohannes** [comment]
maybe @nwaelkens or @TomKeur can add their thoughts about this topic?

**Comment by Nightbr** [comment]
In order to reduce complexity, we can use raw docker-compose for linux Host:

docker-compose.linux.yml

```yaml
version: '2'

services:
    php:
        build:
            context: config/php-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./var/data/uploads/var:/var/www/app/var/uploads
            - ./var/data/uploads/web:/var/www/app/web/uploads
            - ./var/data/indexes:/var/www/app/var/indexes
            - ./var/data/sitemaps:/var/www/app/var/sitemaps
            - ./var/logs/app:/var/www/app/var/logs

            - ./app:/var/www/app
            - cache-volume:/var/www/app/var/cache
            - sessions-volume:/var/www/app/var/sessions
    nginx:
        build: config/nginx
        ports:
            - 10080:80
        volumes_from:
            - php
        volumes:
            - ./var/logs/nginx/:/var/log/nginx
    mysql:
        build: config/mysql
        ports:
            - 13306:3306
        volumes:
            - ./var/data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    elasticsearch:
        build: config/elk/elasticsearch
        ports:
            - 19200:9200
        volumes:
            - ./var/data/elasticsearch:/usr/share/elasticsearch/data
        environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    logstash:
        build: config/elk/logstash
        ports:
            - 19600:9600
        depends_on:
            - elasticsearch
        volumes:
            - ./var/logs:/var/log/other
    kibana:
        build: config/elk/kibana
        ports:
            - 15601:5601
        depends_on:
            - elasticsearch
            - logstash

volumes:
    cache-volume:
        driver_opts:
            type: tmpfs
            device: tmpfs
    sessions-volume:
        driver_opts:
            type: tmpfs
            device: tmpfs
```

I just need to `chmod -R 777 var` in order to write logs, ... I think we should improve this by configure properly user permission (USERID as env pass to the container which execute php with user with the same id to not have permission issues).
